### ISSUE TITLE
Instructions for database connection with analytics software

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Analytics-Module#11]
AS AN Analytic module user
I WANT TO have guidance how to connect chatbot related databases to analytics software
SO THAT I can retrieve the data to the software and create my own custom reports and visualizations, that are not provided by Analytics Module 

### Acceptance Criteria

- [ ] instructions created for connecting the Bürokratt PostgreSQL databases to following analytics softwares: 
1. Power BI https://powerbi.microsoft.com/en-us/ 
2. Tableau https://www.tableau.com/
3. QlickView https://www.qlik.com/us/products/qlikview
- [ ] the instructions are displayed under Reports

**Comment by turnerrainer** [comment]
If this task only requires setting up a connection between OpenSearch and OpenSearch Dashboards then this issue is obsolete.

@PaulaMerle do we have some sample charts we would like to be created? A how-to-guide to go through the data sets we have and how to use them to create OpenSearch Dashboards charts?

**Comment by PaulaMerle** [comment]
Will not be done
